// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCllNXfpBN89KRn5o_jtASu84IGyxNoEzw',
    appId: '1:56811257855:web:d6587656ab9b571e13b1ca',
    messagingSenderId: '56811257855',
    projectId: 'navajeev-e3262',
    authDomain: 'navajeev-e3262.firebaseapp.com',
    storageBucket: 'navajeev-e3262.firebasestorage.app',
    measurementId: 'G-KBBRVLCQ0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeyH4zeLzo5bQQ25Eq6DFNwaGC2-n3X3U',
    appId: '1:56811257855:android:31a41878ccee4c5d13b1ca',
    messagingSenderId: '56811257855',
    projectId: 'navajeev-e3262',
    storageBucket: 'navajeev-e3262.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCllNXfpBN89KRn5o_jtASu84IGyxNoEzw',
    appId: '1:56811257855:web:70a94cff1cd12bfb13b1ca',
    messagingSenderId: '56811257855',
    projectId: 'navajeev-e3262',
    authDomain: 'navajeev-e3262.firebaseapp.com',
    storageBucket: 'navajeev-e3262.firebasestorage.app',
    measurementId: 'G-XC21031FKE',
  );
}
